name: flutter_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  image_picker: ^1.0.5
  path: ^1.8.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_auth: ^4.2.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.2.0
  fluttertoast: ^8.1.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.3.0
  toggle_switch: ^2.0.1
  share_plus: ^6.3.0
  path_provider: ^2.0.11
  screenshot: ^2.1.0
  url_launcher: ^6.1.7
  animated_splash_screen: ^1.3.0
  image_pixels: ^3.0.1
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700